// translator.js - Multi-language translation engine for WildGuard Web
const translations = {
    "English": {
        "app_title": "WildGuard AI",
        "app_tagline": "Smart Wildlife Detection Anywhere",
        "camera_title": "Live Camera Edge Inference",
        "gallery_title": "Gallery Offline Classifier",
        "video_title": "Video Frame-by-Frame Analyzer",
        "audio_title": "Audio Spectrogram CNN",
        "settings_title": "Settings & AI Optimization",
        "capture_btn": "Capture Frame & Detect",
        "run_classification": "Run Classification",
        "deconstruct_video": "Deconstruct & Scan Video (MP4)",
        "record_call": "Record Call",
        "upload_audio": "Upload Audio",
        "select_photo": "Select Random Album Photo",
        "anomaly_detected": "Anomaly Detected",
        "rare_spotted": "Rare Species Spotted",
        "ai_engine": "AI Engine Settings",
        "edge_sim": "Edge Device Simulation Settings",
        "general_pref": "General Preferences",
        "theme_mode": "Theme Mode",
        "display_lang": "Display Language",
        "camera_scan_card": "Camera Scan",
        "gallery_scan_card": "Gallery Scan",
        "video_scan_card": "Video Frame Scan",
        "audio_scan_card": "Audio Classification",
        "view_analytics": "View Analytics Dashboard & Heatmap",
        "quick_scan": "Quick Scan",
        "engines_title": "Detection Engines",
        "welcome": "Welcome",
        "recent_detections": "Recent Detections History",
        "total_detections": "Total Detections",
        "alerts_triggered": "Alerts Triggered",
        "logout": "Logout",
        "admin_panel": "Admin Panel",
        "email": "Email Address",
        "password": "Password",
        "fullName": "Full Name",
        "login_btn": "Sign In",
        "register_btn": "Register Node",
        "guest_btn": "Explore as Guest",
        "forgot_pass": "Forgot Password?",
        "reset_desc": "Offline backup reset key generated: ",
        "have_account": "Already have an account? Sign In",
        "need_account": "Register new node account",
        "guest_name": "Guest Explorer",
        "dashboard_title": "Wildlife Analytics Dashboard",
        "view_heatmap": "Inference Heatmap Density",
        "species_breakdown": "Species Breakdown Percentage",
        "detections_over_time": "Detections Frequency Chart"
    },
    "Telugu": {
        "app_title": "వైల్డ్‌గార్డ్ AI",
        "app_tagline": "స్మార్ట్ వైల్డ్‌లైఫ్ డిటెక్షన్ ఎక్కడైనా",
        "camera_title": "లైవ్ కెమెరా ఎడ్జ్ ఇన్ఫరెన్స్",
        "gallery_title": "గ్యాలరీ ఆఫ్-లైన్ వర్గీకరణ",
        "video_title": "వీడియో ఫ్రేమ్ విశ్లేషణ",
        "audio_title": "ఆడియో స్పెక్ట్రోగ్రామ్ CNN",
        "settings_title": "సెట్టింగులు & AI ఆప్టిమైజేషన్",
        "capture_btn": "ఫ్రేమ్ క్యాప్చర్ & డిటెక్ట్",
        "run_classification": "వర్గీకరణను రన్ చేయి",
        "deconstruct_video": "వీడియో స్కాన్ చేయి (MP4)",
        "record_call": "కాల్ రికార్డ్ చేయి",
        "upload_audio": "ఆడియో అప్‌లోడ్ చేయి",
        "select_photo": "యాదృచ్ఛిక ఆల్బమ్ ఫోటో ఎంచుకోండి",
        "anomaly_detected": "అసాధారణత గుర్తించబడింది",
        "rare_spotted": "అరుదైన జాతి కనిపించింది",
        "ai_engine": "AI ఇంజిన్ సెట్టింగులు",
        "edge_sim": "ఎడ్జ్ పరికర అనుకరణ సెట్టింగులు",
        "general_pref": "సాధారణ ప్రాధాన్యతలు",
        "theme_mode": "థీమ్ మోడ్",
        "display_lang": "ప్రదర్శన భాష",
        "camera_scan_card": "కెమెరా స్కాన్",
        "gallery_scan_card": "గ్యాలరీ స్కాన్",
        "video_scan_card": "వీడియో ఫ్రేమ్ స్కాన్",
        "audio_scan_card": "ఆడియో వర్గీకరణ",
        "view_analytics": "విశ్లేషణల డాష్‌బోర్డ్ & హీట్‌మ్యాప్ చూడండి",
        "quick_scan": "త్వరిత స్కాన్",
        "engines_title": "గుర్తింపు ఇంజిన్లు",
        "welcome": "స్వాగతం",
        "recent_detections": "ఇటీవలి గుర్తింపుల చరిత్ర",
        "total_detections": "మొత్తం గుర్తింపులు",
        "alerts_triggered": "అలర్ట్‌లు రేగాయి",
        "logout": "లాగ్అవుట్",
        "admin_panel": "అడ్మిన్ ప్యానెల్",
        "email": "ఇమెయిల్ చిరునామా",
        "password": "పాస్‌వర్డ్",
        "fullName": "పూర్తి పేరు",
        "login_btn": "సైన్ ఇన్",
        "register_btn": "నోడ్ నమోదు చేసుకోండి",
        "guest_btn": "అతిథిగా అన్వేషించండి",
        "forgot_pass": "పాస్‌వర్డ్ మర్చిపోయారా?",
        "reset_desc": "ఆఫ్‌లైన్ బ్యాకప్ రీసెట్ కీ సృష్టించబడింది: ",
        "have_account": "ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి",
        "need_account": "కొత్త నోడ్ ఖాతాను నమోదు చేయండి",
        "guest_name": "అతిథి అన్వేషకుడు",
        "dashboard_title": "వన్యప్రాణుల విశ్లేషణల డాష్‌బోర్డ్",
        "view_heatmap": "ఇన్ఫరెన్స్ హీట్‌మ్యాప్ డెన్సిటీ",
        "species_breakdown": "జాతుల విశ్లేషణ శాతం",
        "detections_over_time": "గుర్తింపుల ఫ్రీక్వెన్సీ చార్ట్"
    },
    "Hindi": {
        "app_title": "वाइल्डगार्ड AI",
        "app_tagline": "स्मार्ट वन्यजीव पहचान कहीं भी",
        "camera_title": "लाइव कैमरा एज निष्कर्ष",
        "gallery_title": "गैलरी ऑफ़लाइन वर्गीकरण",
        "video_title": "वीडियो फ्रेम-दर-फ्रेम विश्लेषक",
        "audio_title": "ऑडियो स्पेक्ट्रोग्राम CNN",
        "settings_title": "सेटिंग्स और AI अनुकूलन",
        "capture_btn": "फ्रेम कैप्चर और पहचानें",
        "run_classification": "वर्गीकरण चलाएं",
        "deconstruct_video": "वीडियो स्कैन करें (MP4)",
        "record_call": "कॉल रिकॉर्ड करें",
        "upload_audio": "ऑडियो अपलोड करें",
        "select_photo": "रैंडम एल्बम फोटो चुनें",
        "anomaly_detected": "विसंगति का पता चला",
        "rare_spotted": "दुर्लभ प्रजाति देखी गई",
        "ai_engine": "AI इंजन सेटिंग्स",
        "edge_sim": "एज डिवाइस सिमुलेशन सेटिंग्स",
        "general_pref": "सामान्य प्राथमिकताएं",
        "theme_mode": "थीम मोड",
        "display_lang": "प्रदर्शन भाषा",
        "camera_scan_card": "कैमरा स्कैन",
        "gallery_scan_card": "गैलरी स्कैन",
        "video_scan_card": "वीडियो फ्रेम स्कैन",
        "audio_scan_card": "ऑडियो वर्गीकरण",
        "view_analytics": "विश्लेषण डैशबोर्ड और हीटमैप देखें",
        "quick_scan": "त्वरित स्कैन",
        "engines_title": "डिटेक्शन इंजन",
        "welcome": "स्वागत है",
        "recent_detections": "हालिया पहचान इतिहास",
        "total_detections": "कुल पहचान",
        "alerts_triggered": "अलर्ट शुरू हुए",
        "logout": "लॉगआउट",
        "admin_panel": "एडमिन पैनल",
        "email": "ईमेल पता",
        "password": "पासवर्ड",
        "fullName": "पूरा नाम",
        "login_btn": "साइन इन",
        "register_btn": "नोड पंजीकृत करें",
        "guest_btn": "अतिथि के रूप में खोजें",
        "forgot_pass": "पासवर्ड भूल गए?",
        "reset_desc": "ऑफ़लाइन बैकअप रीसेट कुंजी उत्पन्न हुई: ",
        "have_account": "पहले से ही खाता है? साइन इन करें",
        "need_account": "नया नोड खाता पंजीकृत करें",
        "guest_name": "अतिथि एक्सप्लोरर",
        "dashboard_title": "वन्यजीव विश्लेषण डैशबोर्ड",
        "view_heatmap": "निष्कर्ष हीटमैप घनत्व",
        "species_breakdown": "प्रजाति टूटना प्रतिशत",
        "detections_over_time": "पहचान आवृत्ति चार्ट"
    }
};

let currentLanguage = localStorage.getItem('wildguard_lang') || 'English';

export function getLanguage() {
    return currentLanguage;
}

export function setLanguage(lang) {
    if (translations[lang]) {
        currentLanguage = lang;
        localStorage.setItem('wildguard_lang', lang);
    }
}

export function t(key) {
    return translations[currentLanguage]?.[key] || translations['English']?.[key] || key;
}
