// utils.js - Clientside dynamic PDF (jsPDF) & CSV Report Export Utilities
import { t } from './translator.js';

// Show Custom Toast notification message drawer
export function showToast(title, message, type = 'success') {
    const container = document.getElementById('toast-container');
    if (!container) return;

    const toast = document.createElement('div');
    toast.className = `toast ${type}`;

    toast.innerHTML = `
        <div class="toast-content">
            <div class="toast-title">${title}</div>
            <div class="toast-msg">${message}</div>
        </div>
        <button class="toast-close">×</button>
    `;

    container.appendChild(toast);

    // Toast auto close after 4 seconds
    const autoClose = setTimeout(() => {
        toast.style.opacity = '0';
        toast.style.transform = 'translateY(-15px) scale(0.95)';
        setTimeout(() => toast.remove(), 300);
    }, 4000);

    // Manual close bind
    toast.querySelector('.toast-close').addEventListener('click', () => {
        clearTimeout(autoClose);
        toast.remove();
    });
}

// Generate premium branding layout PDF document
export function exportToPdf(detections) {
    if (!window.jspdf) {
        showToast("Export Error", "jsPDF library is not loaded. Ensure you are connected to the network.", "error");
        return;
    }

    try {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        // 1. Forest Green Header block styling
        doc.setFillColor(46, 125, 50); // Forest Green
        doc.rect(0, 0, 220, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(22);
        doc.text("WILDGUARD AI – Wildlife Analytics Report", 15, 25);
        
        doc.setFont("Helvetica", "normal");
        doc.setFontSize(10);
        doc.text("Edge Inference Offline Log Data", 15, 33);

        // 2. Metadata Section
        doc.setFillColor(244, 247, 245); // Light grey background
        doc.rect(10, 45, 190, 20, 'F');
        
        doc.setTextColor(50, 50, 50);
        doc.setFontSize(9);
        const now = new Date().toLocaleString();
        const activeUser = localStorage.getItem('wildguard_active_user') ? JSON.parse(localStorage.getItem('wildguard_active_user')) : { fullName: 'Explorer' };
        doc.text(`Generated On: ${now}`, 15, 52);
        doc.text(`Active Operator: ${activeUser.fullName} (${activeUser.email || 'guest'})`, 15, 58);
        doc.text(`Total Logged Detections: ${detections.length}`, 120, 52);
        doc.text(`Alert Anomalies: ${detections.filter(d => d.status === 'alert').length}`, 120, 58);

        // 3. Draw Table headers
        let startY = 75;
        doc.setFillColor(27, 94, 32); // Dark Green Header
        doc.rect(10, startY, 190, 8, 'F');
        
        doc.setTextColor(255, 255, 255);
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(9);
        doc.text("Time Stamp", 12, startY + 5);
        doc.text("Species", 62, startY + 5);
        doc.text("Scientific Name", 102, startY + 5);
        doc.text("Confidence", 152, startY + 5);
        doc.text("Status", 182, startY + 5);

        // 4. Data Rows
        doc.setTextColor(80, 80, 80);
        doc.setFont("Helvetica", "normal");
        
        if (detections.length === 0) {
            doc.text("No local edge detections logged on this device node.", 15, startY + 15);
        } else {
            detections.slice(0, 18).forEach((det, idx) => { // limit page size
                const rowY = startY + 8 + (idx * 8);
                
                // zebra colors
                if (idx % 2 === 1) {
                    doc.setFillColor(245, 248, 245);
                    doc.rect(10, rowY, 190, 8, 'F');
                }

                // draw border lines
                doc.setDrawColor(220, 220, 220);
                doc.line(10, rowY + 8, 200, rowY + 8);

                const timeStr = new Date(det.timestamp).toLocaleTimeString();
                const dateStr = new Date(det.timestamp).toLocaleDateString();
                
                doc.text(`${dateStr} ${timeStr}`, 12, rowY + 5);
                doc.text(det.species.substring(0, 22), 62, rowY + 5);
                doc.text(det.scientific.substring(0, 22), 102, rowY + 5);
                doc.text(`${(det.confidence * 100).toFixed(1)}%`, 152, rowY + 5);
                doc.text(det.status.toUpperCase(), 182, rowY + 5);
            });
        }

        // 5. Footer signature
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by WildGuard AI Web Node application. Confidential Forest Reserves Data.", 15, 280);

        doc.save(`wildguard_report_${Date.now()}.pdf`);
        showToast("PDF Export Complete", "A PDF wildlife analytics report has been downloaded.", "success");
    } catch (e) {
        console.error("PDF Export Failure", e);
        showToast("PDF Export Failed", "Something went wrong drawing the PDF report.", "error");
    }
}

// Format detections to CSV string and download Blob
export function exportToCsv(detections) {
    if (detections.length === 0) {
        showToast("Export Denied", "No detection log data available to export.", "warning");
        return;
    }

    try {
        const headers = ["ID", "Timestamp", "Species Name", "Scientific Name", "Category", "Confidence Score", "Alert Status"];
        const rows = detections.map(d => [
            d.id,
            d.timestamp,
            `"${d.species}"`,
            `"${d.scientific}"`,
            `"${d.category}"`,
            d.confidence,
            d.status
        ]);

        const csvContent = "data:text/csv;charset=utf-8," 
            + [headers.join(","), ...rows.map(e => e.join(","))].join("\n");

        const encodedUri = encodeURI(csvContent);
        const link = document.createElement("a");
        link.setAttribute("href", encodedUri);
        link.setAttribute("download", `wildguard_detections_${Date.now()}.csv`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);

        showToast("CSV Export Success", "CSV logs successfully formatted and downloaded.", "success");
    } catch (e) {
        console.error("CSV Export Failure", e);
        showToast("CSV Export Failed", "Something went wrong formatting the CSV table.", "error");
    }
}
